config/routes.rb
Letsapp::Application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :pois
  resources :likes
  resources :follows do
    collection do
      post 'follow_poi'
      post 'unfollow_poi'
    end
  end

  root 'home#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/poi.rb
class Poi < ActiveRecord::Base

  mount_uploader :logo, ImageUploader

  acts_as_followable
  acts_as_likeable

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_follower
  acts_as_liker
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  
  def follow_poi
    @poi = Poi.find(params[:poi_id])
    current_user.follow!(@poi)

    respond_to do |format|
      format.js
    end

  end

  def unfollow_poi
    @poi = Poi.find(params[:poi_id])
    current_user.unfollow!(@poi)

    respond_to do |format|
      format.js
    end
    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def home
    @pois = Poi.all
    
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
  
  def show
    @poi = Poi.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pois_helper.rb
module PoisHelper
end

app/views/follows/follow_poi.js.erb
$('#follow_form').html('<%= escape_javascript(render :partial => "pois/shared/follow_form", :locals => {:poi => @poi}) %>');

app/views/follows/unfollow_poi.js.erb
$('#follow_form').html('<%= escape_javascript(render :partial => "pois/shared/follow_form", :locals => {:poi => @poi}) %>');

app/views/home/home.html.erb

<%= render :partial => 'home/shared/pois', :locals => { :pois => @pois } %>


app/views/home/shared/_menu.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<%= root_path%>"><span class="glyphicon glyphicon-home"></span></a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav"></ul>

			<ul class="nav navbar-nav navbar-right">
				<li>
					<% if user_signed_in?%>

					<a lass="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.email%> <span class="caret"></span> </a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
						</li>
					</ul>
					<%else%>
						<%= link_to('Login', new_user_session_path)  %>
					<%end%>
				</li>

			</ul>

		</div>
	</div>
</div>


app/views/home/shared/_pois.html.erb
<% if pois.any? %>

<% pois.in_groups_of(4,false) do |poi_row| %>

<div class="row">

	<% for poi in poi_row %>

	<div id="poi_<%= poi.id %>" class="col-sm-3">
		<div class="panel-heading">
			<h4 class="panel-title text-center"><%= poi.name%></h4>
		</div>
		<div class="panel panel-default panel-no-bottom-margin thumbnail">
			<%= link_to image_tag(poi.logo_url(:thumbnail)), poi_path(poi) if poi.logo? %>
		</div>
		<div class="panel-footer text-center">
			<a href="#like"><span class="glyphicon glyphicon-heart"></span></a>
			<a href="#star"><span class="glyphicon glyphicon-map-marker"></span></a>
		</div>

	</div>

	<%end%>

</div>

<% end %>

<% end %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Letsapp</title>
		<meta name="viewport" content ="width=device-width; initial-scale=1.0;">
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render :partial => 'home/shared/menu' %>
		<div class="body_wrapper">
			<%= yield %>
		</div>

	</body>
</html>

app/views/pois/shared/_follow.html.erb
<h2><strong> <%= poi.followers(User).count %> </strong></h2>
<p>
	<small>Followers</small>
</p>

<%= link_to('Follow', follow_poi_follows_path({:poi_id => poi.id}), :method=> "post", :remote => 'true', :class => "btn btn-success btn-block" )%>


app/views/pois/shared/_follow_form.html.erb
<div id="follow_form">
	<% if user_signed_in?%>
	<% if current_user.follows?(poi) %>
	<%= render 'pois/shared/unfollow', :poi => poi%>
	<% else %>
	<%= render 'pois/shared/follow', :poi => poi %>
	<% end %>
	<% else %>
	<h2><strong> <%= poi.followers(User).count %></strong></h2>
	<p>
		<small>Followers</small>
	</p>
	<%= link_to('Follow', new_user_session_path, :class => "btn btn-success btn-block")%>
	<% end %>
</div>

app/views/pois/shared/_unfollow.html.erb
<h2><strong> <%= poi.followers(User).count %> </strong></h2>
<p>
	<small>Followers</small>
</p>

<%= link_to('UnFollow', unfollow_poi_follows_path({:poi_id => poi.id}), :method=> "post", :remote => 'true', :class => "btn btn-success btn-block" )%>

app/views/pois/show.html.erb
<div class="row">
	<div class="">
		<div class="well panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div class="col-xs-12 col-sm-4 text-center">
						<%= image_tag(@poi.logo_url(:thumbnail),:class=>"center-block img-circle img-thumbnail img-responsive")if @poi.logo?  %>
						<ul class="list-inline ratings text-center" title="Ratings">
							<li>
								<a href="#"><span class="fa fa-star fa-lg"></span></a>
							</li>
							<li>
								<a href="#"><span class="fa fa-star fa-lg"></span></a>
							</li>
							<li>
								<a href="#"><span class="fa fa-star fa-lg"></span></a>
							</li>
							<li>
								<a href="#"><span class="fa fa-star fa-lg"></span></a>
							</li>
							<li>
								<a href="#"><span class="fa fa-star fa-lg"></span></a>
							</li>
						</ul>
					</div>
					<!--/col-->
					<div class="col-xs-12 col-sm-8">
						<h2><%= @poi.name%></h2>
						<p>
							<%= @poi.description%>
						</p>
						<p>
							<strong>Website:</strong>
							<%= @poi.website_url%>
						</p>
						<p>
							<strong>Phone:</strong>
							<%= @poi.phone_number%>
						</p>
						<p>
							<strong>Address:</strong>
							<%= %>
						</p>
						<!-- <p>
						<strong>Tags: </strong>
						<span class="label label-info tags">resort</span>
						<span class="label label-info tags">family</span>
						<span class="label label-info tags">beach</span>
						<span class="label label-info tags">cycling</span>
						</p> -->
					</div>
					<!--/col-->
					<div class="clearfix"></div>
					<div class="col-xs-12 col-sm-4">

						<%= render 'pois/shared/follow_form', :poi => @poi %>

					</div>
					<!--/col-->
					<div class="col-xs-12 col-sm-4">
						<h2><strong>245</strong></h2>
						<p>
							<small>Wanna Go</small>
						</p>
						<button class="btn btn-info btn-block">
							<span class="fa fa-user"></span> Wanna Go
						</button>
					</div>
					<!--/col-->
					<div class="col-xs-12 col-sm-4">
						<h2><strong>43</strong></h2>
						<p>
							<small>Been There</small>
						</p>
						<button type="button" class="btn btn-primary btn-block">
							<span class="fa fa-gear"></span> Been There
						</button>
					</div>
					<!--/col-->
				</div>
				<!--/row-->
			</div>
			<!--/panel-body-->
		</div>
		<!--/panel-->
	</div>
	<!--/col-->
</div>
<!--/row-->
